dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.3.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.3.0'

networks:
  development:
    host: http://127.0.0.1
    port: 7545
  sepolia:
    host: https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID
    chainid: 11155111
    explorer: https://api-sepolia.etherscan.io/api
    gas_price: auto

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
