dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.3.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.3.0'

networks:
  development:
    host: http://127.0.0.1
    port: 7545